// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.ai.formrecognizer.implementation.models;

import com.azure.core.util.ExpandableStringEnum;
import com.fasterxml.jackson.annotation.JsonCreator;
import java.util.Collection;

/** Defines values for AnalyzeResultFormat. */
public final class AnalyzeResultFormat extends ExpandableStringEnum<AnalyzeResultFormat> {
    /** Static value json for AnalyzeResultFormat. */
    public static final AnalyzeResultFormat JSON = fromString("json");

    /** Static value protobuf for AnalyzeResultFormat. */
    public static final AnalyzeResultFormat PROTOBUF = fromString("protobuf");

    /**
     * Creates or finds a AnalyzeResultFormat from its string representation.
     *
     * @param name a name to look for.
     * @return the corresponding AnalyzeResultFormat.
     */
    @JsonCreator
    public static AnalyzeResultFormat fromString(String name) {
        return fromString(name, AnalyzeResultFormat.class);
    }

    /** @return known AnalyzeResultFormat values. */
    public static Collection<AnalyzeResultFormat> values() {
        return values(AnalyzeResultFormat.class);
    }
}
