// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.ai.formrecognizer.implementation.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;

/** Azure Blob Storage content. */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "kind")
@JsonTypeName("azure.blob")
@Fluent
public final class AzureBlobContentSource extends ContentSource {
    /*
     * Azure Blob Storage container URL.
     */
    @JsonProperty(value = "containerUrl", required = true)
    private String containerUrl;

    /*
     * Content path.
     */
    @JsonProperty(value = "path")
    private String path;

    /**
     * Get the containerUrl property: Azure Blob Storage container URL.
     *
     * @return the containerUrl value.
     */
    public String getContainerUrl() {
        return this.containerUrl;
    }

    /**
     * Set the containerUrl property: Azure Blob Storage container URL.
     *
     * @param containerUrl the containerUrl value to set.
     * @return the AzureBlobContentSource object itself.
     */
    public AzureBlobContentSource setContainerUrl(String containerUrl) {
        this.containerUrl = containerUrl;
        return this;
    }

    /**
     * Get the path property: Content path.
     *
     * @return the path value.
     */
    public String getPath() {
        return this.path;
    }

    /**
     * Set the path property: Content path.
     *
     * @param path the path value to set.
     * @return the AzureBlobContentSource object itself.
     */
    public AzureBlobContentSource setPath(String path) {
        this.path = path;
        return this;
    }
}
