// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.ai.formrecognizer.implementation.models;

import com.azure.core.annotation.Fluent;
import com.azure.core.util.CoreUtils;
import com.fasterxml.jackson.annotation.JsonProperty;

/** Content represented via Base64 encoding. */
@Fluent
public final class Base64ContentSource extends ContentSource {
    /*
     * Base64 encoded content data.
     */
    @JsonProperty(value = "data", required = true)
    private byte[] data;

    /**
     * Get the data property: Base64 encoded content data.
     *
     * @return the data value.
     */
    public byte[] getData() {
        return CoreUtils.clone(this.data);
    }

    /**
     * Set the data property: Base64 encoded content data.
     *
     * @param data the data value to set.
     * @return the Base64ContentSource object itself.
     */
    public ContentSource setData(byte[] data) {
        this.data = CoreUtils.clone(data);
        return this;
    }
}
