// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.ai.formrecognizer.implementation.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;

/**
 * A word object consisting of a contiguous sequence of characters. For non-space delimited languages, such as Chinese,
 * Japanese, and Korean, each character is represented as its own word.
 */
@Fluent
public final class DocumentWord {
    /*
     * Text content of the word.
     */
    @JsonProperty(value = "text", required = true)
    private String text;

    /*
     * Bounding box of the word.
     */
    @JsonProperty(value = "boundingBox", required = true)
    private List<Float> boundingBox;

    /*
     * Confidence of correctly extracting the word.
     */
    @JsonProperty(value = "confidence", required = true)
    private float confidence;

    /*
     * Location of the word in the reading order concatenated content.
     */
    @JsonProperty(value = "span", required = true)
    private DocumentSpan span;

    /*
     * Normalized starting horizontal position of each character in the word.
     */
    @JsonProperty(value = "charPositions")
    private List<Float> charPositions;

    /**
     * Get the text property: Text content of the word.
     *
     * @return the text value.
     */
    public String getText() {
        return this.text;
    }

    /**
     * Set the text property: Text content of the word.
     *
     * @param text the text value to set.
     * @return the DocumentWord object itself.
     */
    public DocumentWord setText(String text) {
        this.text = text;
        return this;
    }

    /**
     * Get the boundingBox property: Bounding box of the word.
     *
     * @return the boundingBox value.
     */
    public List<Float> getBoundingBox() {
        return this.boundingBox;
    }

    /**
     * Set the boundingBox property: Bounding box of the word.
     *
     * @param boundingBox the boundingBox value to set.
     * @return the DocumentWord object itself.
     */
    public DocumentWord setBoundingBox(List<Float> boundingBox) {
        this.boundingBox = boundingBox;
        return this;
    }

    /**
     * Get the confidence property: Confidence of correctly extracting the word.
     *
     * @return the confidence value.
     */
    public float getConfidence() {
        return this.confidence;
    }

    /**
     * Set the confidence property: Confidence of correctly extracting the word.
     *
     * @param confidence the confidence value to set.
     * @return the DocumentWord object itself.
     */
    public DocumentWord setConfidence(float confidence) {
        this.confidence = confidence;
        return this;
    }

    /**
     * Get the span property: Location of the word in the reading order concatenated content.
     *
     * @return the span value.
     */
    public DocumentSpan getSpan() {
        return this.span;
    }

    /**
     * Set the span property: Location of the word in the reading order concatenated content.
     *
     * @param span the span value to set.
     * @return the DocumentWord object itself.
     */
    public DocumentWord setSpan(DocumentSpan span) {
        this.span = span;
        return this;
    }

    /**
     * Get the charPositions property: Normalized starting horizontal position of each character in the word.
     *
     * @return the charPositions value.
     */
    public List<Float> getCharPositions() {
        return this.charPositions;
    }

    /**
     * Set the charPositions property: Normalized starting horizontal position of each character in the word.
     *
     * @param charPositions the charPositions value to set.
     * @return the DocumentWord object itself.
     */
    public DocumentWord setCharPositions(List<Float> charPositions) {
        this.charPositions = charPositions;
        return this;
    }
}
