// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.ai.formrecognizer.implementation.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;

/** A block object that describes various layout elements. */
@Fluent
public final class DocumentBlock {
    /*
     * Kind of layout block element.
     */
    @JsonProperty(value = "kind", required = true)
    private VisualElementKind kind;

    /*
     * Concatenated content of the layout block in reading order.
     */
    @JsonProperty(value = "content", required = true)
    private String content;

    /*
     * Bounding box of the layout block element.
     */
    @JsonProperty(value = "boundingBox", required = true)
    private List<Float> boundingBox;

    /*
     * Confidence of correctly extracting the layout block element.
     */
    @JsonProperty(value = "confidence")
    private Float confidence;

    /*
     * Location of the layout block element in the reading order concatenated
     * content.
     */
    @JsonProperty(value = "spans", required = true)
    private List<DocumentSpan> spans;

    /*
     * If the block is split, pointer to the continuation block.
     */
    @JsonProperty(value = "continuation")
    private String continuation;

    /**
     * Get the kind property: Kind of layout block element.
     *
     * @return the kind value.
     */
    public VisualElementKind getKind() {
        return this.kind;
    }

    /**
     * Set the kind property: Kind of layout block element.
     *
     * @param kind the kind value to set.
     * @return the DocumentBlock object itself.
     */
    public DocumentBlock setKind(VisualElementKind kind) {
        this.kind = kind;
        return this;
    }

    /**
     * Get the content property: Concatenated content of the layout block in reading order.
     *
     * @return the content value.
     */
    public String getContent() {
        return this.content;
    }

    /**
     * Set the content property: Concatenated content of the layout block in reading order.
     *
     * @param content the content value to set.
     * @return the DocumentBlock object itself.
     */
    public DocumentBlock setContent(String content) {
        this.content = content;
        return this;
    }

    /**
     * Get the boundingBox property: Bounding box of the layout block element.
     *
     * @return the boundingBox value.
     */
    public List<Float> getBoundingBox() {
        return this.boundingBox;
    }

    /**
     * Set the boundingBox property: Bounding box of the layout block element.
     *
     * @param boundingBox the boundingBox value to set.
     * @return the DocumentBlock object itself.
     */
    public DocumentBlock setBoundingBox(List<Float> boundingBox) {
        this.boundingBox = boundingBox;
        return this;
    }

    /**
     * Get the confidence property: Confidence of correctly extracting the layout block element.
     *
     * @return the confidence value.
     */
    public Float getConfidence() {
        return this.confidence;
    }

    /**
     * Set the confidence property: Confidence of correctly extracting the layout block element.
     *
     * @param confidence the confidence value to set.
     * @return the DocumentBlock object itself.
     */
    public DocumentBlock setConfidence(Float confidence) {
        this.confidence = confidence;
        return this;
    }

    /**
     * Get the spans property: Location of the layout block element in the reading order concatenated content.
     *
     * @return the spans value.
     */
    public List<DocumentSpan> getSpans() {
        return this.spans;
    }

    /**
     * Set the spans property: Location of the layout block element in the reading order concatenated content.
     *
     * @param spans the spans value to set.
     * @return the DocumentBlock object itself.
     */
    public DocumentBlock setSpans(List<DocumentSpan> spans) {
        this.spans = spans;
        return this;
    }

    /**
     * Get the continuation property: If the block is split, pointer to the continuation block.
     *
     * @return the continuation value.
     */
    public String getContinuation() {
        return this.continuation;
    }

    /**
     * Set the continuation property: If the block is split, pointer to the continuation block.
     *
     * @param continuation the continuation value to set.
     * @return the DocumentBlock object itself.
     */
    public DocumentBlock setContinuation(String continuation) {
        this.continuation = continuation;
        return this;
    }
}
