// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.ai.formrecognizer.implementation.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;

/** An object representing various visual elements. */
@Fluent
public final class DocumentVisualElement {
    /*
     * Kind of visual element.
     */
    @JsonProperty(value = "kind")
    private VisualElementKind kind;

    /*
     * Bounding box of the visual element.
     */
    @JsonProperty(value = "boundingBox", required = true)
    private List<Float> boundingBox;

    /*
     * Confidence of correctly extracting the visual element.
     */
    @JsonProperty(value = "confidence")
    private Float confidence;

    /*
     * Location of the visual element in the reading order concatenated
     * content.
     */
    @JsonProperty(value = "span", required = true)
    private DocumentSpan span;

    /**
     * Get the kind property: Kind of visual element.
     *
     * @return the kind value.
     */
    public VisualElementKind getKind() {
        return this.kind;
    }

    /**
     * Set the kind property: Kind of visual element.
     *
     * @param kind the kind value to set.
     * @return the DocumentVisualElement object itself.
     */
    public DocumentVisualElement setKind(VisualElementKind kind) {
        this.kind = kind;
        return this;
    }

    /**
     * Get the boundingBox property: Bounding box of the visual element.
     *
     * @return the boundingBox value.
     */
    public List<Float> getBoundingBox() {
        return this.boundingBox;
    }

    /**
     * Set the boundingBox property: Bounding box of the visual element.
     *
     * @param boundingBox the boundingBox value to set.
     * @return the DocumentVisualElement object itself.
     */
    public DocumentVisualElement setBoundingBox(List<Float> boundingBox) {
        this.boundingBox = boundingBox;
        return this;
    }

    /**
     * Get the confidence property: Confidence of correctly extracting the visual element.
     *
     * @return the confidence value.
     */
    public Float getConfidence() {
        return this.confidence;
    }

    /**
     * Set the confidence property: Confidence of correctly extracting the visual element.
     *
     * @param confidence the confidence value to set.
     * @return the DocumentVisualElement object itself.
     */
    public DocumentVisualElement setConfidence(Float confidence) {
        this.confidence = confidence;
        return this;
    }

    /**
     * Get the span property: Location of the visual element in the reading order concatenated content.
     *
     * @return the span value.
     */
    public DocumentSpan getSpan() {
        return this.span;
    }

    /**
     * Set the span property: Location of the visual element in the reading order concatenated content.
     *
     * @param span the span value to set.
     * @return the DocumentVisualElement object itself.
     */
    public DocumentVisualElement setSpan(DocumentSpan span) {
        this.span = span;
        return this;
    }
}
