// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.ai.formrecognizer.implementation.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.Map;

/** Description of the field semantic schema using a JSON Schema style syntax. */
@Fluent
public final class FieldTypeSchema {
    /*
     * Field type.
     */
    @JsonProperty(value = "type")
    private FieldTypeSchemaType type;

    /*
     * Field type schema of each array element.
     */
    @JsonProperty(value = "items")
    private FieldTypeSchema items;

    /*
     * Named sub-fields of the object field.
     */
    @JsonProperty(value = "properties")
    private Map<String, FieldTypeSchema> properties;

    /**
     * Get the type property: Field type.
     *
     * @return the type value.
     */
    public FieldTypeSchemaType getType() {
        return this.type;
    }

    /**
     * Set the type property: Field type.
     *
     * @param type the type value to set.
     * @return the FieldTypeSchema object itself.
     */
    public FieldTypeSchema setType(FieldTypeSchemaType type) {
        this.type = type;
        return this;
    }

    /**
     * Get the items property: Field type schema of each array element.
     *
     * @return the items value.
     */
    public FieldTypeSchema getItems() {
        return this.items;
    }

    /**
     * Set the items property: Field type schema of each array element.
     *
     * @param items the items value to set.
     * @return the FieldTypeSchema object itself.
     */
    public FieldTypeSchema setItems(FieldTypeSchema items) {
        this.items = items;
        return this;
    }

    /**
     * Get the properties property: Named sub-fields of the object field.
     *
     * @return the properties value.
     */
    public Map<String, FieldTypeSchema> getProperties() {
        return this.properties;
    }

    /**
     * Set the properties property: Named sub-fields of the object field.
     *
     * @param properties the properties value to set.
     * @return the FieldTypeSchema object itself.
     */
    public FieldTypeSchema setProperties(Map<String, FieldTypeSchema> properties) {
        this.properties = properties;
        return this;
    }
}
