// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.ai.formrecognizer.implementation.models;

import com.azure.core.util.ExpandableStringEnum;
import com.fasterxml.jackson.annotation.JsonCreator;
import java.util.Collection;

/** Defines values for FontFamily. */
public final class FontFamily extends ExpandableStringEnum<FontFamily> {
    /** Static value serif for FontFamily. */
    public static final FontFamily SERIF = fromString("serif");

    /** Static value sanSerif for FontFamily. */
    public static final FontFamily SAN_SERIF = fromString("sanSerif");

    /** Static value monospace for FontFamily. */
    public static final FontFamily MONOSPACE = fromString("monospace");

    /** Static value cursive for FontFamily. */
    public static final FontFamily CURSIVE = fromString("cursive");

    /** Static value fantasy for FontFamily. */
    public static final FontFamily FANTASY = fromString("fantasy");

    /**
     * Creates or finds a FontFamily from its string representation.
     *
     * @param name a name to look for.
     * @return the corresponding FontFamily.
     */
    @JsonCreator
    public static FontFamily fromString(String name) {
        return fromString(name, FontFamily.class);
    }

    /** @return known FontFamily values. */
    public static Collection<FontFamily> values() {
        return values(FontFamily.class);
    }
}
