// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.ai.formrecognizer.implementation.models;

import com.azure.core.util.ExpandableStringEnum;
import com.fasterxml.jackson.annotation.JsonCreator;
import java.util.Collection;

/** Defines values for FontStyle. */
public final class FontStyle extends ExpandableStringEnum<FontStyle> {
    /** Static value normal for FontStyle. */
    public static final FontStyle NORMAL = fromString("normal");

    /** Static value italic for FontStyle. */
    public static final FontStyle ITALIC = fromString("italic");

    /**
     * Creates or finds a FontStyle from its string representation.
     *
     * @param name a name to look for.
     * @return the corresponding FontStyle.
     */
    @JsonCreator
    public static FontStyle fromString(String name) {
        return fromString(name, FontStyle.class);
    }

    /** @return known FontStyle values. */
    public static Collection<FontStyle> values() {
        return values(FontStyle.class);
    }
}
