// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.ai.formrecognizer.implementation.models;

import com.azure.core.util.ExpandableStringEnum;
import com.fasterxml.jackson.annotation.JsonCreator;
import java.util.Collection;

/** Defines values for FontWeight. */
public final class FontWeight extends ExpandableStringEnum<FontWeight> {
    /** Static value normal for FontWeight. */
    public static final FontWeight NORMAL = fromString("normal");

    /** Static value bold for FontWeight. */
    public static final FontWeight BOLD = fromString("bold");

    /** Static value light for FontWeight. */
    public static final FontWeight LIGHT = fromString("light");

    /**
     * Creates or finds a FontWeight from its string representation.
     *
     * @param name a name to look for.
     * @return the corresponding FontWeight.
     */
    @JsonCreator
    public static FontWeight fromString(String name) {
        return fromString(name, FontWeight.class);
    }

    /** @return known FontWeight values. */
    public static Collection<FontWeight> values() {
        return values(FontWeight.class);
    }
}
