// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.ai.formrecognizer.implementation.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.Map;

/**
 * The
 * Paths1Mp6JdlDocumentmodelsModelidGetResponses200ContentApplicationJsonSchemaAllof1PropertiesDoctypesAdditionalproperties
 * model.
 */
@Fluent
public final
class Paths1Mp6JdlDocumentmodelsModelidGetResponses200ContentApplicationJsonSchemaAllof1PropertiesDoctypesAdditionalproperties {
    /*
     * Model description.
     */
    @JsonProperty(value = "description")
    private String description;

    /*
     * Description of the document semantic schema using a JSON Schema style
     * syntax.
     */
    @JsonProperty(value = "schema", required = true)
    private Map<String, FieldTypeSchema> schema;

    /*
     * Estimated confidence for each semantic field.
     */
    @JsonProperty(value = "estimatedConfidence")
    private Map<String, Float> estimatedConfidence;

    /**
     * Get the description property: Model description.
     *
     * @return the description value.
     */
    public String getDescription() {
        return this.description;
    }

    /**
     * Set the description property: Model description.
     *
     * @param description the description value to set.
     * @return the
     *     Paths1Mp6JdlDocumentmodelsModelidGetResponses200ContentApplicationJsonSchemaAllof1PropertiesDoctypesAdditionalproperties
     *     object itself.
     */
    public
    Paths1Mp6JdlDocumentmodelsModelidGetResponses200ContentApplicationJsonSchemaAllof1PropertiesDoctypesAdditionalproperties
            setDescription(String description) {
        this.description = description;
        return this;
    }

    /**
     * Get the schema property: Description of the document semantic schema using a JSON Schema style syntax.
     *
     * @return the schema value.
     */
    public Map<String, FieldTypeSchema> getSchema() {
        return this.schema;
    }

    /**
     * Set the schema property: Description of the document semantic schema using a JSON Schema style syntax.
     *
     * @param schema the schema value to set.
     * @return the
     *     Paths1Mp6JdlDocumentmodelsModelidGetResponses200ContentApplicationJsonSchemaAllof1PropertiesDoctypesAdditionalproperties
     *     object itself.
     */
    public
    Paths1Mp6JdlDocumentmodelsModelidGetResponses200ContentApplicationJsonSchemaAllof1PropertiesDoctypesAdditionalproperties
            setSchema(Map<String, FieldTypeSchema> schema) {
        this.schema = schema;
        return this;
    }

    /**
     * Get the estimatedConfidence property: Estimated confidence for each semantic field.
     *
     * @return the estimatedConfidence value.
     */
    public Map<String, Float> getEstimatedConfidence() {
        return this.estimatedConfidence;
    }

    /**
     * Set the estimatedConfidence property: Estimated confidence for each semantic field.
     *
     * @param estimatedConfidence the estimatedConfidence value to set.
     * @return the
     *     Paths1Mp6JdlDocumentmodelsModelidGetResponses200ContentApplicationJsonSchemaAllof1PropertiesDoctypesAdditionalproperties
     *     object itself.
     */
    public
    Paths1Mp6JdlDocumentmodelsModelidGetResponses200ContentApplicationJsonSchemaAllof1PropertiesDoctypesAdditionalproperties
            setEstimatedConfidence(Map<String, Float> estimatedConfidence) {
        this.estimatedConfidence = estimatedConfidence;
        return this;
    }
}
