// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.ai.formrecognizer.implementation.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;

/** The Paths1CndbjaDocumentmodelsGetResponses200ContentApplicationJsonSchema model. */
@Fluent
public final class Paths1CndbjaDocumentmodelsGetResponses200ContentApplicationJsonSchema {
    /*
     * List of models.
     */
    @JsonProperty(value = "value", required = true)
    private List<ModelInfo> value;

    /*
     * Link to the next page of models.
     */
    @JsonProperty(value = "nextLink")
    private String nextLink;

    /**
     * Get the value property: List of models.
     *
     * @return the value value.
     */
    public List<ModelInfo> getValue() {
        return this.value;
    }

    /**
     * Set the value property: List of models.
     *
     * @param value the value value to set.
     * @return the Paths1CndbjaDocumentmodelsGetResponses200ContentApplicationJsonSchema object itself.
     */
    public Paths1CndbjaDocumentmodelsGetResponses200ContentApplicationJsonSchema setValue(List<ModelInfo> value) {
        this.value = value;
        return this;
    }

    /**
     * Get the nextLink property: Link to the next page of models.
     *
     * @return the nextLink value.
     */
    public String getNextLink() {
        return this.nextLink;
    }

    /**
     * Set the nextLink property: Link to the next page of models.
     *
     * @param nextLink the nextLink value to set.
     * @return the Paths1CndbjaDocumentmodelsGetResponses200ContentApplicationJsonSchema object itself.
     */
    public Paths1CndbjaDocumentmodelsGetResponses200ContentApplicationJsonSchema setNextLink(String nextLink) {
        this.nextLink = nextLink;
        return this;
    }
}
