// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.ai.formrecognizer.implementation.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;

/** Request body to train a new custom model. */
@Fluent
public final class Paths1JppyhfDocumentmodelsTrainPostRequestbodyContentApplicationJsonSchema {
    /*
     * Unique model name.
     */
    @JsonProperty(value = "modelId", required = true)
    private String modelId;

    /*
     * Model description.
     */
    @JsonProperty(value = "description")
    private String description;

    /*
     * Training data.
     */
    @JsonProperty(value = "trainSource", required = true)
    private ContentSource trainSource;

    /**
     * Get the modelId property: Unique model name.
     *
     * @return the modelId value.
     */
    public String getModelId() {
        return this.modelId;
    }

    /**
     * Set the modelId property: Unique model name.
     *
     * @param modelId the modelId value to set.
     * @return the Paths1JppyhfDocumentmodelsTrainPostRequestbodyContentApplicationJsonSchema object itself.
     */
    public Paths1JppyhfDocumentmodelsTrainPostRequestbodyContentApplicationJsonSchema setModelId(String modelId) {
        this.modelId = modelId;
        return this;
    }

    /**
     * Get the description property: Model description.
     *
     * @return the description value.
     */
    public String getDescription() {
        return this.description;
    }

    /**
     * Set the description property: Model description.
     *
     * @param description the description value to set.
     * @return the Paths1JppyhfDocumentmodelsTrainPostRequestbodyContentApplicationJsonSchema object itself.
     */
    public Paths1JppyhfDocumentmodelsTrainPostRequestbodyContentApplicationJsonSchema setDescription(
            String description) {
        this.description = description;
        return this;
    }

    /**
     * Get the trainSource property: Training data.
     *
     * @return the trainSource value.
     */
    public ContentSource getTrainSource() {
        return this.trainSource;
    }

    /**
     * Set the trainSource property: Training data.
     *
     * @param trainSource the trainSource value to set.
     * @return the Paths1JppyhfDocumentmodelsTrainPostRequestbodyContentApplicationJsonSchema object itself.
     */
    public Paths1JppyhfDocumentmodelsTrainPostRequestbodyContentApplicationJsonSchema setTrainSource(
            ContentSource trainSource) {
        this.trainSource = trainSource;
        return this;
    }
}
