// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.ai.formrecognizer.implementation.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;

/** The Paths1Ep1Fe8InfoGetResponses200ContentApplicationJsonSchema model. */
@Fluent
public final class Paths1Ep1Fe8InfoGetResponses200ContentApplicationJsonSchema {
    /*
     * The customDocumentModels property.
     */
    @JsonProperty(value = "customDocumentModels", required = true)
    private Paths1D9IbxeInfoGetResponses200ContentApplicationJsonSchemaPropertiesCustomdocumentmodels
            customDocumentModels;

    /**
     * Get the customDocumentModels property: The customDocumentModels property.
     *
     * @return the customDocumentModels value.
     */
    public Paths1D9IbxeInfoGetResponses200ContentApplicationJsonSchemaPropertiesCustomdocumentmodels
            getCustomDocumentModels() {
        return this.customDocumentModels;
    }

    /**
     * Set the customDocumentModels property: The customDocumentModels property.
     *
     * @param customDocumentModels the customDocumentModels value to set.
     * @return the Paths1Ep1Fe8InfoGetResponses200ContentApplicationJsonSchema object itself.
     */
    public Paths1Ep1Fe8InfoGetResponses200ContentApplicationJsonSchema setCustomDocumentModels(
            Paths1D9IbxeInfoGetResponses200ContentApplicationJsonSchemaPropertiesCustomdocumentmodels
                    customDocumentModels) {
        this.customDocumentModels = customDocumentModels;
        return this;
    }
}
