// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.ai.formrecognizer.implementation.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;

/** The PostContentSchemaComponentModelsItem model. */
@Fluent
public final class PostContentSchemaComponentModelsItem {
    /*
     * Unique model name.
     */
    @JsonProperty(value = "modelId", required = true)
    private String modelId;

    /*
     * Optional list of document types from this model to include in the
     * composed model.  If not specified, all document types from this model
     * will be included.
     */
    @JsonProperty(value = "docTypes")
    private List<String> docTypes;

    /**
     * Get the modelId property: Unique model name.
     *
     * @return the modelId value.
     */
    public String getModelId() {
        return this.modelId;
    }

    /**
     * Set the modelId property: Unique model name.
     *
     * @param modelId the modelId value to set.
     * @return the PostContentSchemaComponentModelsItem object itself.
     */
    public PostContentSchemaComponentModelsItem setModelId(String modelId) {
        this.modelId = modelId;
        return this;
    }

    /**
     * Get the docTypes property: Optional list of document types from this model to include in the composed model. If
     * not specified, all document types from this model will be included.
     *
     * @return the docTypes value.
     */
    public List<String> getDocTypes() {
        return this.docTypes;
    }

    /**
     * Set the docTypes property: Optional list of document types from this model to include in the composed model. If
     * not specified, all document types from this model will be included.
     *
     * @param docTypes the docTypes value to set.
     * @return the PostContentSchemaComponentModelsItem object itself.
     */
    public PostContentSchemaComponentModelsItem setDocTypes(List<String> docTypes) {
        this.docTypes = docTypes;
        return this;
    }
}
