// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.ai.formrecognizer.implementation.models;

import com.azure.core.http.HttpHeaders;
import com.azure.core.http.HttpRequest;
import com.azure.core.http.rest.ResponseBase;

/** Contains all response data for the trainModel operation. */
public final class TrainModelResponse extends ResponseBase<TrainModelHeaders, Void> {
    /**
     * Creates an instance of TrainModelResponse.
     *
     * @param request the request which resulted in this TrainModelResponse.
     * @param statusCode the status code of the HTTP response.
     * @param rawHeaders the raw headers of the HTTP response.
     * @param value the deserialized value of the HTTP response.
     * @param headers the deserialized headers of the HTTP response.
     */
    public TrainModelResponse(
            HttpRequest request, int statusCode, HttpHeaders rawHeaders, Void value, TrainModelHeaders headers) {
        super(request, statusCode, rawHeaders, value, headers);
    }
}
