// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.ai.formrecognizer.models;

import com.azure.core.util.ExpandableStringEnum;
import com.fasterxml.jackson.annotation.JsonCreator;

import java.util.Collection;

/** Defines values for FormTableCellKind. */
public final class FormTableCellKind extends ExpandableStringEnum<FormTableCellKind> {
    /** Static value content for FormTableCellKind. */
    public static final FormTableCellKind CONTENT = fromString("content");

    /** Static value rowHeader for FormTableCellKind. */
    public static final FormTableCellKind ROW_HEADER = fromString("rowHeader");

    /** Static value columnHeader for FormTableCellKind. */
    public static final FormTableCellKind COLUMN_HEADER = fromString("columnHeader");

    /** Static value stub for FormTableCellKind. */
    public static final FormTableCellKind STUB = fromString("stub");

    /** Static value description for FormTableCellKind. */
    public static final FormTableCellKind DESCRIPTION = fromString("description");

    /**
     * Creates or finds a FormTableCellKind from its string representation.
     *
     * @param name a name to look for.
     * @return the corresponding FormTableCellKind.
     */
    @JsonCreator
    public static FormTableCellKind fromString(String name) {
        return fromString(name, FormTableCellKind.class);
    }

    /** @return known FormTableCellKind values. */
    public static Collection<FormTableCellKind> values() {
        return values(FormTableCellKind.class);
    }
}
