// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.ai.personalizer;

import com.azure.ai.personalizer.implementation.EventsImpl;
import com.azure.ai.personalizer.models.ErrorResponseException;
import com.azure.ai.personalizer.models.RewardRequest;
import com.azure.core.annotation.ReturnType;
import com.azure.core.annotation.ServiceClient;
import com.azure.core.annotation.ServiceMethod;
import com.azure.core.http.rest.Response;
import com.azure.core.util.Context;

/** Initializes a new instance of the synchronous PersonalizerClient type. */
@ServiceClient(builder = PersonalizerClientBuilder.class)
public final class EventsClient {
    private final EventsImpl serviceClient;

    /**
     * Initializes an instance of Events client.
     *
     * @param serviceClient the service client implementation.
     */
    EventsClient(EventsImpl serviceClient) {
        this.serviceClient = serviceClient;
    }

    /**
     * Report reward between 0 and 1 that resulted from using the action specified in rewardActionId, for the specified
     * event.
     *
     * @param eventId The event id this reward applies to.
     * @param reward The reward should be a floating point number, typically between 0 and 1.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws ErrorResponseException thrown if the request is rejected by server.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     */
    @ServiceMethod(returns = ReturnType.SINGLE)
    public void reward(String eventId, RewardRequest reward) {
        this.serviceClient.reward(eventId, reward);
    }

    /**
     * Report reward between 0 and 1 that resulted from using the action specified in rewardActionId, for the specified
     * event.
     *
     * @param eventId The event id this reward applies to.
     * @param reward The reward should be a floating point number, typically between 0 and 1.
     * @param context The context to associate with this operation.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws ErrorResponseException thrown if the request is rejected by server.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return the response.
     */
    @ServiceMethod(returns = ReturnType.SINGLE)
    public Response<Void> rewardWithResponse(String eventId, RewardRequest reward, Context context) {
        return this.serviceClient.rewardWithResponse(eventId, reward, context);
    }

    /**
     * Report that the specified event was actually used (e.g. by being displayed to the user) and a reward should be
     * expected for it.
     *
     * @param eventId The event ID to be activated.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws ErrorResponseException thrown if the request is rejected by server.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     */
    @ServiceMethod(returns = ReturnType.SINGLE)
    public void activate(String eventId) {
        this.serviceClient.activate(eventId);
    }

    /**
     * Report that the specified event was actually used (e.g. by being displayed to the user) and a reward should be
     * expected for it.
     *
     * @param eventId The event ID to be activated.
     * @param context The context to associate with this operation.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws ErrorResponseException thrown if the request is rejected by server.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return the response.
     */
    @ServiceMethod(returns = ReturnType.SINGLE)
    public Response<Void> activateWithResponse(String eventId, Context context) {
        return this.serviceClient.activateWithResponse(eventId, context);
    }
}
