// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.ai.personalizer;

import com.azure.ai.personalizer.implementation.LogsImpl;
import com.azure.ai.personalizer.models.ErrorResponseException;
import com.azure.ai.personalizer.models.LogsProperties;
import com.azure.core.annotation.ReturnType;
import com.azure.core.annotation.ServiceClient;
import com.azure.core.annotation.ServiceMethod;
import com.azure.core.exception.HttpResponseException;
import com.azure.core.http.rest.Response;
import com.azure.core.util.Context;
import java.nio.ByteBuffer;
import reactor.core.publisher.Flux;

/** Initializes a new instance of the synchronous PersonalizerClient type. */
@ServiceClient(builder = PersonalizerClientBuilder.class)
public final class LogClient {
    private final LogsImpl serviceClient;

    /**
     * Initializes an instance of Logs client.
     *
     * @param serviceClient the service client implementation.
     */
    LogClient(LogsImpl serviceClient) {
        this.serviceClient = serviceClient;
    }

    /**
     * The endpoint is intended to be used from within a SDK for logging interactions and accepts specific format
     * defined in https://github.com/VowpalWabbit/reinforcement_learning. This endpoint should not be used by the
     * customer.
     *
     * @param body Interactions binary payload.
     * @param contentLength The contentLength parameter.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws ErrorResponseException thrown if the request is rejected by server.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     */
    @ServiceMethod(returns = ReturnType.SINGLE)
    public void interactions(Flux<ByteBuffer> body, long contentLength) {
        this.serviceClient.interactions(body, contentLength);
    }

    /**
     * The endpoint is intended to be used from within a SDK for logging interactions and accepts specific format
     * defined in https://github.com/VowpalWabbit/reinforcement_learning. This endpoint should not be used by the
     * customer.
     *
     * @param body Interactions binary payload.
     * @param contentLength The contentLength parameter.
     * @param context The context to associate with this operation.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws ErrorResponseException thrown if the request is rejected by server.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return the response.
     */
    @ServiceMethod(returns = ReturnType.SINGLE)
    public Response<Void> interactionsWithResponse(Flux<ByteBuffer> body, long contentLength, Context context) {
        return this.serviceClient.interactionsWithResponse(body, contentLength, context);
    }

    /**
     * The endpoint is intended to be used from within a SDK for logging observations and accepts specific format
     * defined in https://github.com/VowpalWabbit/reinforcement_learning. This endpoint should not be used by the
     * customer.
     *
     * @param body Observations binary payload.
     * @param contentLength The contentLength parameter.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws ErrorResponseException thrown if the request is rejected by server.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     */
    @ServiceMethod(returns = ReturnType.SINGLE)
    public void observations(Flux<ByteBuffer> body, long contentLength) {
        this.serviceClient.observations(body, contentLength);
    }

    /**
     * The endpoint is intended to be used from within a SDK for logging observations and accepts specific format
     * defined in https://github.com/VowpalWabbit/reinforcement_learning. This endpoint should not be used by the
     * customer.
     *
     * @param body Observations binary payload.
     * @param contentLength The contentLength parameter.
     * @param context The context to associate with this operation.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws ErrorResponseException thrown if the request is rejected by server.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return the response.
     */
    @ServiceMethod(returns = ReturnType.SINGLE)
    public Response<Void> observationsWithResponse(Flux<ByteBuffer> body, long contentLength, Context context) {
        return this.serviceClient.observationsWithResponse(body, contentLength, context);
    }

    /**
     * Delete all logs of Rank and Reward calls stored by Personalizer.
     *
     * @throws HttpResponseException thrown if the request is rejected by server.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     */
    @ServiceMethod(returns = ReturnType.SINGLE)
    public void delete() {
        this.serviceClient.delete();
    }

    /**
     * Delete all logs of Rank and Reward calls stored by Personalizer.
     *
     * @param context The context to associate with this operation.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws HttpResponseException thrown if the request is rejected by server.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return the response.
     */
    @ServiceMethod(returns = ReturnType.SINGLE)
    public Response<Void> deleteWithResponse(Context context) {
        return this.serviceClient.deleteWithResponse(context);
    }

    /**
     * Get properties of the Personalizer logs.
     *
     * @throws ErrorResponseException thrown if the request is rejected by server.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return properties of the Personalizer logs.
     */
    @ServiceMethod(returns = ReturnType.SINGLE)
    public LogsProperties getProperties() {
        return this.serviceClient.getProperties();
    }

    /**
     * Get properties of the Personalizer logs.
     *
     * @param context The context to associate with this operation.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws ErrorResponseException thrown if the request is rejected by server.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return properties of the Personalizer logs.
     */
    @ServiceMethod(returns = ReturnType.SINGLE)
    public Response<LogsProperties> getPropertiesWithResponse(Context context) {
        return this.serviceClient.getPropertiesWithResponse(context);
    }
}
