// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.ai.personalizer;

import com.azure.ai.personalizer.implementation.MultiSlotEventsImpl;
import com.azure.ai.personalizer.models.ErrorResponseException;
import com.azure.ai.personalizer.models.MultiSlotRewardRequest;
import com.azure.core.annotation.ReturnType;
import com.azure.core.annotation.ServiceClient;
import com.azure.core.annotation.ServiceMethod;
import com.azure.core.http.rest.Response;
import com.azure.core.util.Context;

/** Initializes a new instance of the synchronous PersonalizerClient type. */
@ServiceClient(builder = PersonalizerClientBuilder.class)
public final class MultiSlotEventsClient {
    private final MultiSlotEventsImpl serviceClient;

    /**
     * Initializes an instance of MultiSlotEvents client.
     *
     * @param serviceClient the service client implementation.
     */
    MultiSlotEventsClient(MultiSlotEventsImpl serviceClient) {
        this.serviceClient = serviceClient;
    }

    /**
     * Report reward that resulted from using the action specified in rewardActionId for the slot.
     *
     * @param eventId The event id this reward applies to.
     * @param body List of slot id and reward values. The reward should be a floating point number, typically between 0
     *     and 1.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws ErrorResponseException thrown if the request is rejected by server.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     */
    @ServiceMethod(returns = ReturnType.SINGLE)
    public void reward(String eventId, MultiSlotRewardRequest body) {
        this.serviceClient.reward(eventId, body);
    }

    /**
     * Report reward that resulted from using the action specified in rewardActionId for the slot.
     *
     * @param eventId The event id this reward applies to.
     * @param body List of slot id and reward values. The reward should be a floating point number, typically between 0
     *     and 1.
     * @param context The context to associate with this operation.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws ErrorResponseException thrown if the request is rejected by server.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return the response.
     */
    @ServiceMethod(returns = ReturnType.SINGLE)
    public Response<Void> rewardWithResponse(String eventId, MultiSlotRewardRequest body, Context context) {
        return this.serviceClient.rewardWithResponse(eventId, body, context);
    }

    /**
     * Report that the specified event was actually used or displayed to the user and a rewards should be expected for
     * it.
     *
     * @param eventId The event ID this activation applies to.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws ErrorResponseException thrown if the request is rejected by server.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     */
    @ServiceMethod(returns = ReturnType.SINGLE)
    public void activate(String eventId) {
        this.serviceClient.activate(eventId);
    }

    /**
     * Report that the specified event was actually used or displayed to the user and a rewards should be expected for
     * it.
     *
     * @param eventId The event ID this activation applies to.
     * @param context The context to associate with this operation.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws ErrorResponseException thrown if the request is rejected by server.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return the response.
     */
    @ServiceMethod(returns = ReturnType.SINGLE)
    public Response<Void> activateWithResponse(String eventId, Context context) {
        return this.serviceClient.activateWithResponse(eventId, context);
    }
}
