// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.ai.personalizer;

import com.azure.ai.personalizer.implementation.PersonalizerClientImpl;
import com.azure.core.annotation.ServiceClientBuilder;
import com.azure.core.http.HttpClient;
import com.azure.core.http.HttpPipeline;
import com.azure.core.http.HttpPipelineBuilder;
import com.azure.core.http.policy.CookiePolicy;
import com.azure.core.http.policy.HttpLogOptions;
import com.azure.core.http.policy.HttpLoggingPolicy;
import com.azure.core.http.policy.HttpPipelinePolicy;
import com.azure.core.http.policy.HttpPolicyProviders;
import com.azure.core.http.policy.RetryPolicy;
import com.azure.core.http.policy.UserAgentPolicy;
import com.azure.core.util.Configuration;
import com.azure.core.util.serializer.JacksonAdapter;
import com.azure.core.util.serializer.SerializerAdapter;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/** A builder for creating a new instance of the PersonalizerClient type. */
@ServiceClientBuilder(
        serviceClients = {
            PersonalizerClient.class,
            ServiceConfigurationClient.class,
            PolicyClient.class,
            EvaluationsClient.class,
            EventsClient.class,
            LogClient.class,
            ModelClient.class,
            MultiSlotEventsClient.class,
            MultiSlotClient.class,
            PersonalizerAsyncClient.class,
            ServiceConfigurationAsyncClient.class,
            PolicyAsyncClient.class,
            EvaluationsAsyncClient.class,
            EventsAsyncClient.class,
            LogAsyncClient.class,
            ModelAsyncClient.class,
            MultiSlotEventsAsyncClient.class,
            MultiSlotAsyncClient.class
        })
public final class PersonalizerClientBuilder {
    private static final String SDK_NAME = "name";

    private static final String SDK_VERSION = "version";

    static final String[] DEFAULT_SCOPES = new String[] {"https://cognitiveservices.azure.com/.default"};

    private final Map<String, String> properties = new HashMap<>();

    /** Create an instance of the PersonalizerClientBuilder. */
    public PersonalizerClientBuilder() {
        this.pipelinePolicies = new ArrayList<>();
    }

    /*
     * Supported Cognitive Services endpoint.
     */
    private String endpoint;

    /**
     * Sets Supported Cognitive Services endpoint.
     *
     * @param endpoint the endpoint value.
     * @return the PersonalizerClientBuilder.
     */
    public PersonalizerClientBuilder endpoint(String endpoint) {
        this.endpoint = endpoint;
        return this;
    }

    /*
     * The HTTP pipeline to send requests through
     */
    private HttpPipeline pipeline;

    /**
     * Sets The HTTP pipeline to send requests through.
     *
     * @param pipeline the pipeline value.
     * @return the PersonalizerClientBuilder.
     */
    public PersonalizerClientBuilder pipeline(HttpPipeline pipeline) {
        this.pipeline = pipeline;
        return this;
    }

    /*
     * The serializer to serialize an object into a string
     */
    private SerializerAdapter serializerAdapter;

    /**
     * Sets The serializer to serialize an object into a string.
     *
     * @param serializerAdapter the serializerAdapter value.
     * @return the PersonalizerClientBuilder.
     */
    public PersonalizerClientBuilder serializerAdapter(SerializerAdapter serializerAdapter) {
        this.serializerAdapter = serializerAdapter;
        return this;
    }

    /*
     * The HTTP client used to send the request.
     */
    private HttpClient httpClient;

    /**
     * Sets The HTTP client used to send the request.
     *
     * @param httpClient the httpClient value.
     * @return the PersonalizerClientBuilder.
     */
    public PersonalizerClientBuilder httpClient(HttpClient httpClient) {
        this.httpClient = httpClient;
        return this;
    }

    /*
     * The configuration store that is used during construction of the service
     * client.
     */
    private Configuration configuration;

    /**
     * Sets The configuration store that is used during construction of the service client.
     *
     * @param configuration the configuration value.
     * @return the PersonalizerClientBuilder.
     */
    public PersonalizerClientBuilder configuration(Configuration configuration) {
        this.configuration = configuration;
        return this;
    }

    /*
     * The logging configuration for HTTP requests and responses.
     */
    private HttpLogOptions httpLogOptions;

    /**
     * Sets The logging configuration for HTTP requests and responses.
     *
     * @param httpLogOptions the httpLogOptions value.
     * @return the PersonalizerClientBuilder.
     */
    public PersonalizerClientBuilder httpLogOptions(HttpLogOptions httpLogOptions) {
        this.httpLogOptions = httpLogOptions;
        return this;
    }

    /*
     * The retry policy that will attempt to retry failed requests, if
     * applicable.
     */
    private RetryPolicy retryPolicy;

    /**
     * Sets The retry policy that will attempt to retry failed requests, if applicable.
     *
     * @param retryPolicy the retryPolicy value.
     * @return the PersonalizerClientBuilder.
     */
    public PersonalizerClientBuilder retryPolicy(RetryPolicy retryPolicy) {
        this.retryPolicy = retryPolicy;
        return this;
    }

    /*
     * The list of Http pipeline policies to add.
     */
    private final List<HttpPipelinePolicy> pipelinePolicies;

    /**
     * Adds a custom Http pipeline policy.
     *
     * @param customPolicy The custom Http pipeline policy to add.
     * @return the PersonalizerClientBuilder.
     */
    public PersonalizerClientBuilder addPolicy(HttpPipelinePolicy customPolicy) {
        pipelinePolicies.add(customPolicy);
        return this;
    }

    /**
     * Builds an instance of PersonalizerClientImpl with the provided parameters.
     *
     * @return an instance of PersonalizerClientImpl.
     */
    private PersonalizerClientImpl buildInnerClient() {
        if (pipeline == null) {
            this.pipeline = createHttpPipeline();
        }
        if (serializerAdapter == null) {
            this.serializerAdapter = JacksonAdapter.createDefaultSerializerAdapter();
        }
        PersonalizerClientImpl client = new PersonalizerClientImpl(pipeline, serializerAdapter, endpoint);
        return client;
    }

    private HttpPipeline createHttpPipeline() {
        Configuration buildConfiguration =
                (configuration == null) ? Configuration.getGlobalConfiguration() : configuration;
        if (httpLogOptions == null) {
            httpLogOptions = new HttpLogOptions();
        }
        List<HttpPipelinePolicy> policies = new ArrayList<>();
        String clientName = properties.getOrDefault(SDK_NAME, "UnknownName");
        String clientVersion = properties.getOrDefault(SDK_VERSION, "UnknownVersion");
        policies.add(
                new UserAgentPolicy(httpLogOptions.getApplicationId(), clientName, clientVersion, buildConfiguration));
        HttpPolicyProviders.addBeforeRetryPolicies(policies);
        policies.add(retryPolicy == null ? new RetryPolicy() : retryPolicy);
        policies.add(new CookiePolicy());
        policies.addAll(this.pipelinePolicies);
        HttpPolicyProviders.addAfterRetryPolicies(policies);
        policies.add(new HttpLoggingPolicy(httpLogOptions));
        HttpPipeline httpPipeline =
                new HttpPipelineBuilder()
                        .policies(policies.toArray(new HttpPipelinePolicy[0]))
                        .httpClient(httpClient)
                        .build();
        return httpPipeline;
    }

    /**
     * Builds an instance of PersonalizerAsyncClient async client.
     *
     * @return an instance of PersonalizerAsyncClient.
     */
    public PersonalizerAsyncClient buildPersonalizerAsyncClient() {
        return new PersonalizerAsyncClient(buildInnerClient());
    }

    /**
     * Builds an instance of ServiceConfigurationAsyncClient async client.
     *
     * @return an instance of ServiceConfigurationAsyncClient.
     */
    public ServiceConfigurationAsyncClient buildServiceConfigurationAsyncClient() {
        return new ServiceConfigurationAsyncClient(buildInnerClient().getServiceConfigurations());
    }

    /**
     * Builds an instance of PolicyAsyncClient async client.
     *
     * @return an instance of PolicyAsyncClient.
     */
    public PolicyAsyncClient buildPolicyAsyncClient() {
        return new PolicyAsyncClient(buildInnerClient().getPolicies());
    }

    /**
     * Builds an instance of EvaluationsAsyncClient async client.
     *
     * @return an instance of EvaluationsAsyncClient.
     */
    public EvaluationsAsyncClient buildEvaluationsAsyncClient() {
        return new EvaluationsAsyncClient(buildInnerClient().getEvaluations());
    }

    /**
     * Builds an instance of EventsAsyncClient async client.
     *
     * @return an instance of EventsAsyncClient.
     */
    public EventsAsyncClient buildEventsAsyncClient() {
        return new EventsAsyncClient(buildInnerClient().getEvents());
    }

    /**
     * Builds an instance of LogAsyncClient async client.
     *
     * @return an instance of LogAsyncClient.
     */
    public LogAsyncClient buildLogAsyncClient() {
        return new LogAsyncClient(buildInnerClient().getLogs());
    }

    /**
     * Builds an instance of ModelAsyncClient async client.
     *
     * @return an instance of ModelAsyncClient.
     */
    public ModelAsyncClient buildModelAsyncClient() {
        return new ModelAsyncClient(buildInnerClient().getModels());
    }

    /**
     * Builds an instance of MultiSlotEventsAsyncClient async client.
     *
     * @return an instance of MultiSlotEventsAsyncClient.
     */
    public MultiSlotEventsAsyncClient buildMultiSlotEventsAsyncClient() {
        return new MultiSlotEventsAsyncClient(buildInnerClient().getMultiSlotEvents());
    }

    /**
     * Builds an instance of MultiSlotAsyncClient async client.
     *
     * @return an instance of MultiSlotAsyncClient.
     */
    public MultiSlotAsyncClient buildMultiSlotAsyncClient() {
        return new MultiSlotAsyncClient(buildInnerClient().getMultiSlots());
    }

    /**
     * Builds an instance of PersonalizerClient sync client.
     *
     * @return an instance of PersonalizerClient.
     */
    public PersonalizerClient buildPersonalizerClient() {
        return new PersonalizerClient(buildInnerClient());
    }

    /**
     * Builds an instance of ServiceConfigurationClient sync client.
     *
     * @return an instance of ServiceConfigurationClient.
     */
    public ServiceConfigurationClient buildServiceConfigurationClient() {
        return new ServiceConfigurationClient(buildInnerClient().getServiceConfigurations());
    }

    /**
     * Builds an instance of PolicyClient sync client.
     *
     * @return an instance of PolicyClient.
     */
    public PolicyClient buildPolicyClient() {
        return new PolicyClient(buildInnerClient().getPolicies());
    }

    /**
     * Builds an instance of EvaluationsClient sync client.
     *
     * @return an instance of EvaluationsClient.
     */
    public EvaluationsClient buildEvaluationsClient() {
        return new EvaluationsClient(buildInnerClient().getEvaluations());
    }

    /**
     * Builds an instance of EventsClient sync client.
     *
     * @return an instance of EventsClient.
     */
    public EventsClient buildEventsClient() {
        return new EventsClient(buildInnerClient().getEvents());
    }

    /**
     * Builds an instance of LogClient sync client.
     *
     * @return an instance of LogClient.
     */
    public LogClient buildLogClient() {
        return new LogClient(buildInnerClient().getLogs());
    }

    /**
     * Builds an instance of ModelClient sync client.
     *
     * @return an instance of ModelClient.
     */
    public ModelClient buildModelClient() {
        return new ModelClient(buildInnerClient().getModels());
    }

    /**
     * Builds an instance of MultiSlotEventsClient sync client.
     *
     * @return an instance of MultiSlotEventsClient.
     */
    public MultiSlotEventsClient buildMultiSlotEventsClient() {
        return new MultiSlotEventsClient(buildInnerClient().getMultiSlotEvents());
    }

    /**
     * Builds an instance of MultiSlotClient sync client.
     *
     * @return an instance of MultiSlotClient.
     */
    public MultiSlotClient buildMultiSlotClient() {
        return new MultiSlotClient(buildInnerClient().getMultiSlots());
    }
}
