// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.ai.personalizer;

import com.azure.ai.personalizer.implementation.PoliciesImpl;
import com.azure.ai.personalizer.models.ErrorResponseException;
import com.azure.ai.personalizer.models.PolicyContract;
import com.azure.core.annotation.ReturnType;
import com.azure.core.annotation.ServiceClient;
import com.azure.core.annotation.ServiceMethod;
import com.azure.core.exception.HttpResponseException;
import com.azure.core.http.rest.Response;
import reactor.core.publisher.Mono;

/** Initializes a new instance of the asynchronous PersonalizerClient type. */
@ServiceClient(builder = PersonalizerClientBuilder.class, isAsync = true)
public final class PolicyAsyncClient {
    private final PoliciesImpl serviceClient;

    /**
     * Initializes an instance of Policies client.
     *
     * @param serviceClient the service client implementation.
     */
    PolicyAsyncClient(PoliciesImpl serviceClient) {
        this.serviceClient = serviceClient;
    }

    /**
     * Get the Learning Settings currently used by the Personalizer service.
     *
     * @throws HttpResponseException thrown if the request is rejected by server.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return the Learning Settings currently used by the Personalizer service.
     */
    @ServiceMethod(returns = ReturnType.SINGLE)
    public Mono<Response<PolicyContract>> getWithResponse() {
        return this.serviceClient.getWithResponseAsync();
    }

    /**
     * Get the Learning Settings currently used by the Personalizer service.
     *
     * @throws HttpResponseException thrown if the request is rejected by server.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return the Learning Settings currently used by the Personalizer service.
     */
    @ServiceMethod(returns = ReturnType.SINGLE)
    public Mono<PolicyContract> get() {
        return this.serviceClient.getAsync();
    }

    /**
     * Update the Learning Settings that the Personalizer service will use to train models.
     *
     * @param policy The learning settings.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws ErrorResponseException thrown if the request is rejected by server.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return learning settings specifying how to train the model.
     */
    @ServiceMethod(returns = ReturnType.SINGLE)
    public Mono<Response<PolicyContract>> updateWithResponse(PolicyContract policy) {
        return this.serviceClient.updateWithResponseAsync(policy);
    }

    /**
     * Update the Learning Settings that the Personalizer service will use to train models.
     *
     * @param policy The learning settings.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws ErrorResponseException thrown if the request is rejected by server.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return learning settings specifying how to train the model.
     */
    @ServiceMethod(returns = ReturnType.SINGLE)
    public Mono<PolicyContract> update(PolicyContract policy) {
        return this.serviceClient.updateAsync(policy);
    }

    /**
     * Resets the learning settings of the Personalizer service to default.
     *
     * @throws HttpResponseException thrown if the request is rejected by server.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return learning settings specifying how to train the model.
     */
    @ServiceMethod(returns = ReturnType.SINGLE)
    public Mono<Response<PolicyContract>> resetWithResponse() {
        return this.serviceClient.resetWithResponseAsync();
    }

    /**
     * Resets the learning settings of the Personalizer service to default.
     *
     * @throws HttpResponseException thrown if the request is rejected by server.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return learning settings specifying how to train the model.
     */
    @ServiceMethod(returns = ReturnType.SINGLE)
    public Mono<PolicyContract> reset() {
        return this.serviceClient.resetAsync();
    }
}
