// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.ai.personalizer;

import com.azure.ai.personalizer.implementation.ServiceConfigurationsImpl;
import com.azure.ai.personalizer.models.ErrorResponseException;
import com.azure.ai.personalizer.models.PolicyReferenceContract;
import com.azure.ai.personalizer.models.ServiceConfiguration;
import com.azure.core.annotation.ReturnType;
import com.azure.core.annotation.ServiceClient;
import com.azure.core.annotation.ServiceMethod;
import com.azure.core.exception.HttpResponseException;
import com.azure.core.http.rest.Response;
import com.azure.core.util.Context;

/** Initializes a new instance of the synchronous PersonalizerClient type. */
@ServiceClient(builder = PersonalizerClientBuilder.class)
public final class ServiceConfigurationClient {
    private final ServiceConfigurationsImpl serviceClient;

    /**
     * Initializes an instance of ServiceConfigurations client.
     *
     * @param serviceClient the service client implementation.
     */
    ServiceConfigurationClient(ServiceConfigurationsImpl serviceClient) {
        this.serviceClient = serviceClient;
    }

    /**
     * Get the Personalizer service configuration.
     *
     * @throws HttpResponseException thrown if the request is rejected by server.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return the Personalizer service configuration.
     */
    @ServiceMethod(returns = ReturnType.SINGLE)
    public ServiceConfiguration get() {
        return this.serviceClient.get();
    }

    /**
     * Get the Personalizer service configuration.
     *
     * @param context The context to associate with this operation.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws HttpResponseException thrown if the request is rejected by server.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return the Personalizer service configuration.
     */
    @ServiceMethod(returns = ReturnType.SINGLE)
    public Response<ServiceConfiguration> getWithResponse(Context context) {
        return this.serviceClient.getWithResponse(context);
    }

    /**
     * Update the Personalizer service configuration.
     *
     * @param config The personalizer service configuration.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws ErrorResponseException thrown if the request is rejected by server.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return the configuration of the service.
     */
    @ServiceMethod(returns = ReturnType.SINGLE)
    public ServiceConfiguration update(ServiceConfiguration config) {
        return this.serviceClient.update(config);
    }

    /**
     * Update the Personalizer service configuration.
     *
     * @param config The personalizer service configuration.
     * @param context The context to associate with this operation.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws ErrorResponseException thrown if the request is rejected by server.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return the configuration of the service.
     */
    @ServiceMethod(returns = ReturnType.SINGLE)
    public Response<ServiceConfiguration> updateWithResponse(ServiceConfiguration config, Context context) {
        return this.serviceClient.updateWithResponse(config, context);
    }

    /**
     * Apply Learning Settings and model from a pre-existing Offline Evaluation, making them the current online Learning
     * Settings and model and replacing the previous ones.
     *
     * @param body Reference to the policy within the evaluation.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws ErrorResponseException thrown if the request is rejected by server.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     */
    @ServiceMethod(returns = ReturnType.SINGLE)
    public void applyFromEvaluation(PolicyReferenceContract body) {
        this.serviceClient.applyFromEvaluation(body);
    }

    /**
     * Apply Learning Settings and model from a pre-existing Offline Evaluation, making them the current online Learning
     * Settings and model and replacing the previous ones.
     *
     * @param body Reference to the policy within the evaluation.
     * @param context The context to associate with this operation.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws ErrorResponseException thrown if the request is rejected by server.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return the response.
     */
    @ServiceMethod(returns = ReturnType.SINGLE)
    public Response<Void> applyFromEvaluationWithResponse(PolicyReferenceContract body, Context context) {
        return this.serviceClient.applyFromEvaluationWithResponse(body, context);
    }
}
