// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.ai.formrecognizer.v3.implementation.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;

/** Request body to build a new custom model. */
@Fluent
public final class BuildDocumentModelRequest {
    /*
     * Unique model name.
     */
    @JsonProperty(value = "modelId", required = true)
    private String modelId;

    /*
     * Model description.
     */
    @JsonProperty(value = "description")
    private String description;

    /*
     * Technique for building a custom model.
     */
    @JsonProperty(value = "technique", required = true)
    private DocumentModelBuildTechnique technique;

    /*
     * Training data.
     */
    @JsonProperty(value = "source", required = true)
    private ContentSource source;

    /**
     * Get the modelId property: Unique model name.
     *
     * @return the modelId value.
     */
    public String getModelId() {
        return this.modelId;
    }

    /**
     * Set the modelId property: Unique model name.
     *
     * @param modelId the modelId value to set.
     * @return the BuildDocumentModelRequest object itself.
     */
    public BuildDocumentModelRequest setModelId(String modelId) {
        this.modelId = modelId;
        return this;
    }

    /**
     * Get the description property: Model description.
     *
     * @return the description value.
     */
    public String getDescription() {
        return this.description;
    }

    /**
     * Set the description property: Model description.
     *
     * @param description the description value to set.
     * @return the BuildDocumentModelRequest object itself.
     */
    public BuildDocumentModelRequest setDescription(String description) {
        this.description = description;
        return this;
    }

    /**
     * Get the technique property: Technique for building a custom model.
     *
     * @return the technique value.
     */
    public DocumentModelBuildTechnique getTechnique() {
        return this.technique;
    }

    /**
     * Set the technique property: Technique for building a custom model.
     *
     * @param technique the technique value to set.
     * @return the BuildDocumentModelRequest object itself.
     */
    public BuildDocumentModelRequest setTechnique(DocumentModelBuildTechnique technique) {
        this.technique = technique;
        return this;
    }

    /**
     * Get the source property: Training data.
     *
     * @return the source value.
     */
    public ContentSource getSource() {
        return this.source;
    }

    /**
     * Set the source property: Training data.
     *
     * @param source the source value to set.
     * @return the BuildDocumentModelRequest object itself.
     */
    public BuildDocumentModelRequest setSource(ContentSource source) {
        this.source = source;
        return this;
    }
}
