// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.ai.formrecognizer.v3.implementation.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.Map;

/** The Components70NzpzSchemasModelinfoPropertiesDoctypesAdditionalproperties model. */
@Fluent
public final class Components70NzpzSchemasModelinfoPropertiesDoctypesAdditionalproperties {
    /*
     * Model description.
     */
    @JsonProperty(value = "description")
    private String description;

    /*
     * Technique for building a custom model.
     */
    @JsonProperty(value = "technique")
    private DocumentModelBuildTechnique technique;

    /*
     * Description of the document semantic schema using a JSON Schema style
     * syntax.
     */
    @JsonProperty(value = "fieldSchema", required = true)
    private Map<String, FieldTypeSchema> fieldSchema;

    /*
     * Estimated confidence for each field.
     */
    @JsonProperty(value = "fieldConfidence")
    private Map<String, Float> fieldConfidence;

    /**
     * Get the description property: Model description.
     *
     * @return the description value.
     */
    public String getDescription() {
        return this.description;
    }

    /**
     * Set the description property: Model description.
     *
     * @param description the description value to set.
     * @return the Components70NzpzSchemasModelinfoPropertiesDoctypesAdditionalproperties object itself.
     */
    public Components70NzpzSchemasModelinfoPropertiesDoctypesAdditionalproperties setDescription(String description) {
        this.description = description;
        return this;
    }

    /**
     * Get the technique property: Technique for building a custom model.
     *
     * @return the technique value.
     */
    public DocumentModelBuildTechnique getTechnique() {
        return this.technique;
    }

    /**
     * Set the technique property: Technique for building a custom model.
     *
     * @param technique the technique value to set.
     * @return the Components70NzpzSchemasModelinfoPropertiesDoctypesAdditionalproperties object itself.
     */
    public Components70NzpzSchemasModelinfoPropertiesDoctypesAdditionalproperties setTechnique(
            DocumentModelBuildTechnique technique) {
        this.technique = technique;
        return this;
    }

    /**
     * Get the fieldSchema property: Description of the document semantic schema using a JSON Schema style syntax.
     *
     * @return the fieldSchema value.
     */
    public Map<String, FieldTypeSchema> getFieldSchema() {
        return this.fieldSchema;
    }

    /**
     * Set the fieldSchema property: Description of the document semantic schema using a JSON Schema style syntax.
     *
     * @param fieldSchema the fieldSchema value to set.
     * @return the Components70NzpzSchemasModelinfoPropertiesDoctypesAdditionalproperties object itself.
     */
    public Components70NzpzSchemasModelinfoPropertiesDoctypesAdditionalproperties setFieldSchema(
            Map<String, FieldTypeSchema> fieldSchema) {
        this.fieldSchema = fieldSchema;
        return this;
    }

    /**
     * Get the fieldConfidence property: Estimated confidence for each field.
     *
     * @return the fieldConfidence value.
     */
    public Map<String, Float> getFieldConfidence() {
        return this.fieldConfidence;
    }

    /**
     * Set the fieldConfidence property: Estimated confidence for each field.
     *
     * @param fieldConfidence the fieldConfidence value to set.
     * @return the Components70NzpzSchemasModelinfoPropertiesDoctypesAdditionalproperties object itself.
     */
    public Components70NzpzSchemasModelinfoPropertiesDoctypesAdditionalproperties setFieldConfidence(
            Map<String, Float> fieldConfidence) {
        this.fieldConfidence = fieldConfidence;
        return this;
    }
}
