// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.ai.formrecognizer.v3.implementation.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;

/** The GetInfoResponse model. */
@Fluent
public final class GetInfoResponse {
    /*
     * Info regarding custom document models.
     */
    @JsonProperty(value = "customDocumentModels", required = true)
    private GetInfoResponseCustomDocumentModels customDocumentModels;

    /**
     * Get the customDocumentModels property: Info regarding custom document models.
     *
     * @return the customDocumentModels value.
     */
    public GetInfoResponseCustomDocumentModels getCustomDocumentModels() {
        return this.customDocumentModels;
    }

    /**
     * Set the customDocumentModels property: Info regarding custom document models.
     *
     * @param customDocumentModels the customDocumentModels value to set.
     * @return the GetInfoResponse object itself.
     */
    public GetInfoResponse setCustomDocumentModels(GetInfoResponseCustomDocumentModels customDocumentModels) {
        this.customDocumentModels = customDocumentModels;
        return this;
    }
}
