// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.ai.formrecognizer.v3.implementation.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;

/** The Paths1F37K28OperationsOperationidGetResponses200ContentApplicationJsonSchemaAllof1 model. */
@Fluent
public class Paths1F37K28OperationsOperationidGetResponses200ContentApplicationJsonSchemaAllof1 {
    /*
     * Encountered error.
     */
    @JsonProperty(value = "error")
    private Error error;

    /*
     * Operation result upon success.
     */
    @JsonProperty(value = "result")
    private Object result;

    /**
     * Get the error property: Encountered error.
     *
     * @return the error value.
     */
    public Error getError() {
        return this.error;
    }

    /**
     * Set the error property: Encountered error.
     *
     * @param error the error value to set.
     * @return the Paths1F37K28OperationsOperationidGetResponses200ContentApplicationJsonSchemaAllof1 object itself.
     */
    public Paths1F37K28OperationsOperationidGetResponses200ContentApplicationJsonSchemaAllof1 setError(Error error) {
        this.error = error;
        return this;
    }

    /**
     * Get the result property: Operation result upon success.
     *
     * @return the result value.
     */
    public Object getResult() {
        return this.result;
    }

    /**
     * Set the result property: Operation result upon success.
     *
     * @param result the result value to set.
     * @return the Paths1F37K28OperationsOperationidGetResponses200ContentApplicationJsonSchemaAllof1 object itself.
     */
    public Paths1F37K28OperationsOperationidGetResponses200ContentApplicationJsonSchemaAllof1 setResult(Object result) {
        this.result = result;
        return this;
    }
}
