// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.ai.formrecognizer.v3.implementation.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;

/** Document analysis parameters. */
@Fluent
public final class PathsC1W0ZoDocumentmodelsModelidAnalyzePostRequestbodyContentApplicationOctetStreamSchema {
    /*
     * Documents to analyze.
     */
    @JsonProperty(value = "source")
    private ContentSource source;

    /**
     * Get the source property: Documents to analyze.
     *
     * @return the source value.
     */
    public ContentSource getSource() {
        return this.source;
    }

    /**
     * Set the source property: Documents to analyze.
     *
     * @param source the source value to set.
     * @return the PathsC1W0ZoDocumentmodelsModelidAnalyzePostRequestbodyContentApplicationOctetStreamSchema object
     *     itself.
     */
    public PathsC1W0ZoDocumentmodelsModelidAnalyzePostRequestbodyContentApplicationOctetStreamSchema setSource(
            ContentSource source) {
        this.source = source;
        return this;
    }
}
